[package]
name = "sytog-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
sytog-domain = { path = "../sytog-domain" }
thiserror.workspace = true

[lints]
workspace = true

