[package]
name = "sytog-transport"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
futures-util.workspace = true
serde.workspace = true
serde_json.workspace = true
sytog-domain = { path = "../sytog-domain" }
sytog-protocol = { path = "../sytog-protocol" }
thiserror.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true

[lints]
workspace = true
