[package]
name = "sytog-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde_json.workspace = true
sytog-capabilities = { path = "../sytog-capabilities" }
wasm-bindgen.workspace = true

[lints]
workspace = true

